#!/bin/sh

case $(hostname -s) in
	"fauix05")
		DESKS_FIRST="web code cod3 term more"
		DESKS_SECOND="x y z 9 comm"
		bspc monitor HDMI1 -d $DESKS_FIRST
		bspc monitor HDMI2 -d $DESKS_SECOND
		bspc config -m HDMI1 bottom_padding 34
		# bspc monitor HDMI2 --pad 0 0 20 0
		;;

	"Gaia")
		DESKS="web code files comm $(seq 5 9) 0"
		bspc monitor -d $DESKS
		bspc config -m DVI-I-1 bottom_padding 34
		;;
esac

bspc config split_ratio 0.50
bspc config border_width 2
bspc config window_gap 8
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config auto_cancel true

bspc config focused_border_color "#508F50"
bspc config normal_border_color "#3F3E3B"
bspc config presel_border_color "#FF003F"
bspc config active_frame_opacity 0
bspc config normal_frame_opacity 0
bspc config focused_frame_opacity 0.2

$HOME/.config/bspwm/bspwm_rules

