#! /bin/sh

if ! rulc -l > /dev/null ; then
    (setsid ruld &)
    while ! rulc -l > /dev/null ; do
        sleep 0.1
    done
fi

rules=$(rulc -l)
if [ -z "$rules" ] ; then
    rulc -a 'class=="Gimp"' 'desktop=^8, follow=on, floating=on'
    rulc -a 'class=="Chromium"' 'desktop=^2'
    rulc -a 'instance=="mpv"' 'floating=on'
    rulc -a 'class=="Kupfer.py"' 'focus=on'
    rulc -a 'class=="Screenkey"' 'manage=off'

	rulc -a 'class=="Gimp"' 'floating=on'
	rulc -a 'class=="TightVNC"' 'floating=on'
	rulc -a 'class=="Dia"' 'floating=on'
	rulc -a 'class=="screenkey"' 'unmanage=on'
	rulc -a 'class=="BSPWM_FRAME"' 'frame=on'
fi
