#! /bin/sh
bspc rule -a mpv floating=on
bspc rule -a Screenkey manage=off
bspc rule -a Gimp floating=on
bspc rule -a TightVNC floating=on
bspc rule -a Dia floating=on
bspc rule -a BSPWM_FRAME frame=on
bspc rule -a Whatpulse floating=on
