#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# keybindings
Mod=Mod4

hc keyunbind --all

hc keybind $Mod-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-x close
hc keybind $Mod-Return spawn gnome-terminal
hc keybind $Mod-Control-Return spawn dmenu_run
hc keybind $Mod-f spawn firefox
hc keybind $Mod-e spawn nautilus
#hc keybind $Mod-Control-Return spawn gmrun

# colors and settings
hc set frame_border_active_color '#0371AA'
hc set frame_border_normal_color '#00324C'
hc set frame_bg_transparent '1'
#hc set frame_bg_normal_color '#BD9768'
#hc set frame_bg_active_color '#BD8541'
hc set frame_border_width 2
hc set window_border_width 2
hc set window_border_normal_color '#7B9B77'
hc set window_border_active_color '#51DC43'

hc set default_frame_layout 2


# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

hc load 1 '(split horizontal:0.800000:0 (clients max:0) (clients vertical:0)))))'

hc keybind $Mod-Left spawn $XDG_CONFIG_HOME/herbstluftwm/prevTag.sh
hc keybind $Mod-Right spawn $XDG_CONFIG_HOME/herbstluftwm/nextTag.sh

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-bar split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-minus split horizontal 0.5
hc keybind $Mod-plus split vertical 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-t pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc set focus_follows_mouse 1

#hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind Mod1-c cycle     #cycle windows in one frame with alt-tab
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class='file_progress' pseudotile=on
hc rule class='Plugin-container' fullscreen=on
hc rule class='Gmrun' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off


feh --bg-fill Wallpaper/wallpaper-1095561.jpg

trayer --SetDockType true --widthtype pixel --width 300 --edge top --align right --heighttype pixel --height 18 --transparent true --tint 0x000000 --alpha 0 &

$XDG_CONFIG_HOME/herbstluftwm/panel.sh &

